//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ГОРОДА
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ГОРОДА()
        {
            this.КОНТРАГЕНТЫ = new HashSet<КОНТРАГЕНТЫ>();
        }
    
        public int код { get; set; }
        public string наименование { get; set; }
        public Nullable<int> регионы { get; set; }
    
        public virtual РЕГИОНЫ РЕГИОНЫ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КОНТРАГЕНТЫ> КОНТРАГЕНТЫ { get; set; }
    }
}
