//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТИПЫ_ШАБЛОНОВ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТИПЫ_ШАБЛОНОВ()
        {
            this.ШАБЛОНЫ = new HashSet<ШАБЛОНЫ>();
        }
    
        public int код { get; set; }
        public string наименование { get; set; }
        public string запрос { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ШАБЛОНЫ> ШАБЛОНЫ { get; set; }
    }
}
