//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migration.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТРАНСПОРТ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТРАНСПОРТ()
        {
            this.СДЕЛКИ = new HashSet<СДЕЛКИ>();
        }
    
        public int код { get; set; }
        public string гос_номер { get; set; }
        public Nullable<int> марки { get; set; }
        public Nullable<int> модели { get; set; }
        public Nullable<int> категории_транспорта { get; set; }
        public string изготовитель { get; set; }
        public string год { get; set; }
        public string цвет { get; set; }
        public string вин { get; set; }
        public string кузов { get; set; }
        public string шасси { get; set; }
        public string масса { get; set; }
        public string макс_масса { get; set; }
        public string серия_птс { get; set; }
        public string номер_птс { get; set; }
        public Nullable<System.DateTime> дата_птс { get; set; }
        public string кем_птс { get; set; }
        public byte[] копия_птс { get; set; }
        public string серия_стс { get; set; }
        public string номер_стс { get; set; }
        public string кем_стс { get; set; }
        public Nullable<System.DateTime> дата_стс { get; set; }
        public byte[] копия_стс { get; set; }
        public string марка_двиг { get; set; }
        public Nullable<int> типы_двигателей { get; set; }
        public string мощность { get; set; }
        public string па { get; set; }
        public string объем { get; set; }
        public Nullable<int> виды_транспорта { get; set; }
        public string копия_птс_наим { get; set; }
        public string копия_стс_наим { get; set; }
    
        public virtual ВИДЫ_ТРАНСПОРТА ВИДЫ_ТРАНСПОРТА1 { get; set; }
        public virtual КАТЕГОРИИ_ТРАНСПОРТА КАТЕГОРИИ_ТРАНСПОРТА1 { get; set; }
        public virtual МАРКИ МАРКИ1 { get; set; }
        public virtual МОДЕЛИ МОДЕЛИ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СДЕЛКИ> СДЕЛКИ { get; set; }
        public virtual ТИПЫ_ДВИГАТЕЛЕЙ ТИПЫ_ДВИГАТЕЛЕЙ1 { get; set; }
    }
}
