//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankReportClients
    {
        public int Id { get; set; }
        public bool Used { get; set; }
        public int ClientReportId { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public Nullable<int> BankStatus_Id { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual BankStatus BankStatus { get; set; }
        public virtual ClientReports ClientReports { get; set; }
    }
}
