//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientReports()
        {
            this.BankReportClients = new HashSet<BankReportClients>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Source { get; set; }
        public string FullName { get; set; }
        public string Trancport { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> TotalContribution { get; set; }
        public int ClientStatusId { get; set; }
        public string Telefon { get; set; }
        public int CreditProgrammId { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public bool CommissionKnow { get; set; }
        public Nullable<decimal> CommissionRemoval { get; set; }
        public Nullable<bool> CommissionCredit { get; set; }
        public Nullable<decimal> ActAssessment { get; set; }
        public string DKP_DK { get; set; }
        public string Comment { get; set; }
        public string CommissionSalon { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankReportClients> BankReportClients { get; set; }
        public virtual ClientStatus ClientStatus { get; set; }
        public virtual CreditProgramms CreditProgramms { get; set; }
        public virtual Users Users { get; set; }
    }
}
