//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contractors()
        {
            this.CashTransactions = new HashSet<CashTransactions>();
            this.CashTransactions1 = new HashSet<CashTransactions>();
            this.CashTransactions2 = new HashSet<CashTransactions>();
            this.CommissionTransactions = new HashSet<CommissionTransactions>();
            this.CommissionTransactions1 = new HashSet<CommissionTransactions>();
            this.CommissionTransactions2 = new HashSet<CommissionTransactions>();
            this.CreditTransactions = new HashSet<CreditTransactions>();
            this.CreditTransactions1 = new HashSet<CreditTransactions>();
            this.CreditTransactions2 = new HashSet<CreditTransactions>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstNameGenitive { get; set; }
        public string LastNameGenitive { get; set; }
        public string MiddleNameGenitive { get; set; }
        public System.DateTime DateBirth { get; set; }
        public int RegionId { get; set; }
        public int CityId { get; set; }
        public string Raion { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Housing { get; set; }
        public string Apartment { get; set; }
        public string Telefon { get; set; }
        public string NumberDocument { get; set; }
        public string SerialDocument { get; set; }
        public string ByDocument { get; set; }
        public Nullable<System.DateTime> DateDocument { get; set; }
        public int DocumentId { get; set; }
        public int PhotoId { get; set; }
        public int LegalPersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransactions> CashTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransactions> CashTransactions2 { get; set; }
        public virtual Cities Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionTransactions> CommissionTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionTransactions> CommissionTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionTransactions> CommissionTransactions2 { get; set; }
        public virtual LegalPersons LegalPersons { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual UserFiles UserFiles { get; set; }
        public virtual UserFiles UserFiles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactions> CreditTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactions> CreditTransactions2 { get; set; }
    }
}
