//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTransactions
    {
        public int Id { get; set; }
        public int AgentDocumentId { get; set; }
        public int DkpDocumentId { get; set; }
        public System.DateTime DateAgent { get; set; }
        public System.DateTime DateDkp { get; set; }
        public decimal PriceBank { get; set; }
        public decimal DownPayment { get; set; }
        public decimal CreditSumm { get; set; }
        public decimal RealPrice { get; set; }
        public decimal DownPaymentCashbox { get; set; }
        public int CreditorId { get; set; }
        public int RequisitId { get; set; }
        public decimal ReportInsurance { get; set; }
        public decimal Rollback { get; set; }
        public string Source { get; set; }
        public bool IsCredit { get; set; }
        public decimal CommissionCashbox { get; set; }
        public Nullable<System.DateTime> DateProxy { get; set; }
        public string NumberProxy { get; set; }
        public string NumberRegistry { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
        public int SellerId { get; set; }
        public int BuyerId { get; set; }
        public int TrancportId { get; set; }
        public decimal Price { get; set; }
        public int UserId { get; set; }
    
        public virtual Contractors Contractors { get; set; }
        public virtual Contractors Contractors1 { get; set; }
        public virtual Contractors Contractors2 { get; set; }
        public virtual Creditors Creditors { get; set; }
        public virtual Requisits Requisits { get; set; }
        public virtual Trancports Trancports { get; set; }
        public virtual UserFiles UserFiles { get; set; }
        public virtual UserFiles UserFiles1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
