//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aimp3Entities : DbContext
    {
        public aimp3Entities()
            : base("name=aimp3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<BankReportClients> BankReportClients { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<BankStatus> BankStatus { get; set; }
        public virtual DbSet<CashTransactions> CashTransactions { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<ClientReports> ClientReports { get; set; }
        public virtual DbSet<ClientStatus> ClientStatus { get; set; }
        public virtual DbSet<CommissionTransactions> CommissionTransactions { get; set; }
        public virtual DbSet<Contractors> Contractors { get; set; }
        public virtual DbSet<Creditors> Creditors { get; set; }
        public virtual DbSet<CreditProgramms> CreditProgramms { get; set; }
        public virtual DbSet<CreditTransactions> CreditTransactions { get; set; }
        public virtual DbSet<EngineTypes> EngineTypes { get; set; }
        public virtual DbSet<LegalPersons> LegalPersons { get; set; }
        public virtual DbSet<MakeTrancports> MakeTrancports { get; set; }
        public virtual DbSet<ModelTrancports> ModelTrancports { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<ReportTemplates> ReportTemplates { get; set; }
        public virtual DbSet<Requisits> Requisits { get; set; }
        public virtual DbSet<TrancportCategories> TrancportCategories { get; set; }
        public virtual DbSet<Trancports> Trancports { get; set; }
        public virtual DbSet<TrancportTypes> TrancportTypes { get; set; }
        public virtual DbSet<UserFiles> UserFiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
