//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trancports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trancports()
        {
            this.CashTransactions = new HashSet<CashTransactions>();
            this.CommissionTransactions = new HashSet<CommissionTransactions>();
            this.CreditTransactions = new HashSet<CreditTransactions>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int MakeId { get; set; }
        public int ModelId { get; set; }
        public int CategoryId { get; set; }
        public int TypeId { get; set; }
        public string Maker { get; set; }
        public short Year { get; set; }
        public string Color { get; set; }
        public string Vin { get; set; }
        public string BodyNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string Mass { get; set; }
        public string MaxMass { get; set; }
        public string SerialPts { get; set; }
        public string NumberPts { get; set; }
        public Nullable<System.DateTime> DatePts { get; set; }
        public string ByPts { get; set; }
        public int CopyPtsId { get; set; }
        public string SerialSts { get; set; }
        public string NumberSts { get; set; }
        public Nullable<System.DateTime> DateSts { get; set; }
        public string BySts { get; set; }
        public int CopyStsId { get; set; }
        public int EngineTypeId { get; set; }
        public string EngineMake { get; set; }
        public string Strong { get; set; }
        public string Pa { get; set; }
        public string Volume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionTransactions> CommissionTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }
        public virtual EngineTypes EngineTypes { get; set; }
        public virtual MakeTrancports MakeTrancports { get; set; }
        public virtual ModelTrancports ModelTrancports { get; set; }
        public virtual TrancportCategories TrancportCategories { get; set; }
        public virtual TrancportTypes TrancportTypes { get; set; }
        public virtual UserFiles UserFiles { get; set; }
        public virtual UserFiles UserFiles1 { get; set; }
    }
}
