//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class БАНКИ_ДЛЯ_ОТЧЁТЫ_КЛИЕНТОВ
    {
        public int код { get; set; }
        public Nullable<int> спр_банки_отчёты_клиентов { get; set; }
        public Nullable<int> спр_статусы_банка { get; set; }
        public Nullable<byte> используется { get; set; }
        public Nullable<int> отчёты_клиентов { get; set; }
    
        public virtual ОТЧЁТЫ_КЛИЕНТОВ ОТЧЁТЫ_КЛИЕНТОВ1 { get; set; }
        public virtual спр_БАНКИ_ОТЧЁТЫ_КЛИЕНТОВ спр_БАНКИ_ОТЧЁТЫ_КЛИЕНТОВ1 { get; set; }
        public virtual спр_СТАТУСЫ_БАНКА спр_СТАТУСЫ_БАНКА1 { get; set; }
    }
}
