//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class КОНТРАГЕНТЫ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public КОНТРАГЕНТЫ()
        {
            this.СДЕЛКИ = new HashSet<СДЕЛКИ>();
            this.СДЕЛКИ1 = new HashSet<СДЕЛКИ>();
            this.СДЕЛКИ2 = new HashSet<СДЕЛКИ>();
        }
    
        public int код { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string фамилия_р { get; set; }
        public string имя_р { get; set; }
        public string отчество_р { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public Nullable<int> регионы { get; set; }
        public Nullable<int> города { get; set; }
        public string район { get; set; }
        public string улица { get; set; }
        public string дом { get; set; }
        public string корпус { get; set; }
        public string квартира { get; set; }
        public string телефон { get; set; }
        public string номер_док { get; set; }
        public string серия_док { get; set; }
        public string кем_док { get; set; }
        public Nullable<System.DateTime> дата_док { get; set; }
        public byte[] документ { get; set; }
        public byte[] фото { get; set; }
        public byte юр { get; set; }
        public string наименование { get; set; }
        public string инн { get; set; }
        public string огрн { get; set; }
        public string кпп { get; set; }
        public string рас_счет { get; set; }
        public string кор_счет { get; set; }
        public string бик { get; set; }
        public string банк { get; set; }
        public string документ_наим { get; set; }
        public string фото_наим { get; set; }
    
        public virtual ГОРОДА ГОРОДА1 { get; set; }
        public virtual РЕГИОНЫ РЕГИОНЫ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СДЕЛКИ> СДЕЛКИ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СДЕЛКИ> СДЕЛКИ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СДЕЛКИ> СДЕЛКИ2 { get; set; }
    }
}
