//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class спр_СТАТУСЫ_КЛИЕНТОВ
    {
        public int код { get; set; }
        public string наименование { get; set; }
        public Nullable<byte> фильтр { get; set; }
    }
}
