//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDb2Vto3V
{
    using System;
    using System.Collections.Generic;
    
    public partial class ШАБЛОНЫ
    {
        public int код { get; set; }
        public byte[] файл { get; set; }
        public string наименование { get; set; }
        public Nullable<int> типы_шаблонов { get; set; }
        public string файл_наим { get; set; }
    
        public virtual ТИПЫ_ШАБЛОНОВ ТИПЫ_ШАБЛОНОВ1 { get; set; }
    }
}
