//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aimp2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class БАНКИ_ДЛЯ_ОТЧЁТЫ_КЛИЕНТОВ
    {
        public int код { get; set; }
        public Nullable<int> спр_банки_отчёты_клиентов { get; set; }
        public Nullable<int> спр_статусы_банка { get; set; }
        public Nullable<byte> используется { get; set; }
        public Nullable<int> отчёты_клиентов { get; set; }
    
        public virtual ОТЧЁТЫ_КЛИЕНТОВ ОТЧЁТЫ_КЛИЕНТОВ1 { get; set; }
        public virtual спр_БАНКИ_ОТЧЁТЫ_КЛИЕНТОВ спр_БАНКИ_ОТЧЁТЫ_КЛИЕНТОВ1 { get; set; }
        public virtual спр_СТАТУСЫ_БАНКА спр_СТАТУСЫ_БАНКА1 { get; set; }
    }
}
