//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aimp2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПОЛЬЗОВАТЕЛИ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПОЛЬЗОВАТЕЛИ()
        {
            this.ОТЧЁТЫ_КЛИЕНТОВ = new HashSet<ОТЧЁТЫ_КЛИЕНТОВ>();
            this.СДЕЛКИ = new HashSet<СДЕЛКИ>();
        }
    
        public int код { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string отчёство { get; set; }
        public string имя_р { get; set; }
        public string фамилия_р { get; set; }
        public string отчество_р { get; set; }
        public string номер { get; set; }
        public string дата { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public Nullable<byte> админ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОТЧЁТЫ_КЛИЕНТОВ> ОТЧЁТЫ_КЛИЕНТОВ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СДЕЛКИ> СДЕЛКИ { get; set; }
    }
}
