//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aimp2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class РЕКВИЗИТЫ
    {
        public int код { get; set; }
        public string наименование { get; set; }
        public string рос_счет { get; set; }
        public string кор_счет { get; set; }
        public string в_банке { get; set; }
        public string бик { get; set; }
    }
}
