//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aimp2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ШАБЛОНЫ
    {
        public int код { get; set; }
        public byte[] файл { get; set; }
        public string наименование { get; set; }
        public Nullable<int> типы_шаблонов { get; set; }
        public string файл_наим { get; set; }
    
        public virtual ТИПЫ_ШАБЛОНОВ ТИПЫ_ШАБЛОНОВ1 { get; set; }
    }
}
